#include "globaldefinitions.h"

const std::unordered_map<DWORD, std::string> keyMap = {
		{VK_LBUTTON,    "鼠标左键"},
		{VK_RBUTTON,    "鼠标右键"},
		{VK_MBUTTON,    "鼠标中键"},
		{VK_BACK,       "退格"},
		{VK_TAB,        "TAB"},
		{VK_RETURN,     "回车"},
		{VK_SHIFT,      "SHIFT"},
		{VK_CONTROL,    "CTRL"},
		{VK_CAPITAL,    "CL"},
		{VK_ESCAPE,     "ESC"},
		{VK_SPACE,      "空格"},
		{VK_PRIOR,      "PGUP"},
		{VK_NEXT,       "PGDN"},
		{VK_END,        "END"},
		{VK_HOME,       "HOME"},
		{VK_LEFT,       "LEFT"},
		{VK_UP,         "UP"},
		{VK_RIGHT,      "RIGHT"},
		{VK_DOWN,       "DOWN"},
		{VK_SELECT,     "SEL"},
		{VK_SNAPSHOT,   "截屏"},
		{VK_DELETE,     "DEL"},
		{0x30,          "0"},
		{0x31,          "1"},
		{0x32,          "2"},
		{0x33,          "3"},
		{0x34,          "4"},
		{0x35,          "5"},
		{0x36,          "6"},
		{0x37,          "7"},
		{0x38,          "8"},
		{0x39,          "9"},
		{0x41,          "A"},
		{0x42,          "B"},
		{0x43,          "C"},
		{0x44,          "D"},
		{0x45,          "E"},
		{0x46,          "F"},
		{0x47,          "G"},
		{0x48,          "H"},
		{0x49,          "I"},
		{0x4A,          "J"},
		{0x4B,          "K"},
		{0x4C,          "L"},
		{0x4D,          "M"},
		{0x4E,          "N"},
		{0x4F,          "O"},
		{0x50,          "P"},
		{0x51,          "Q"},
		{0x52,          "R"},
		{0x53,          "S"},
		{0x54,          "T"},
		{0x55,          "U"},
		{0x56,          "V"},
		{0x57,          "W"},
		{0x58,          "X"},
		{0x59,          "Y"},
		{0x5A,          "Z"},
		{VK_LWIN,       "LWIN"},
		{VK_RWIN,       "RWIN"},
		{VK_NUMPAD0,    "NUM 0"},
		{VK_NUMPAD1,    "NUM 1"},
		{VK_NUMPAD2,    "NUM 2"},
		{VK_NUMPAD3,    "NUM 3"},
		{VK_NUMPAD4,    "NUM 4"},
		{VK_NUMPAD5,    "NUM 5"},
		{VK_NUMPAD6,    "NUM 6"},
		{VK_NUMPAD7,    "NUM 7"},
		{VK_NUMPAD8,    "NUM 8"},
		{VK_NUMPAD9,    "NUM 9"},
		{VK_F1,         "F1"},
		{VK_F2,         "F2"},
		{VK_F3,         "F3"},
		{VK_F4,         "F4"},
		{VK_F5,         "F5"},
		{VK_F6,         "F6"},
		{VK_F7,         "F7"},
		{VK_F8,         "F8"},
		{VK_F9,         "F9"},
		{VK_F10,        "F10"},
		{VK_F11,        "F11"},
		{VK_F12,        "F12"},
		{VK_NUMLOCK,    "NL"},
		{VK_LSHIFT,     "LSHFT"},
		{VK_RSHIFT,     "RSHFT"},
		{VK_LCONTROL,   "LCTRL"},
		{VK_RCONTROL,   "RCTRL"},
		{VK_OEM_1,      ";"},
		{VK_OEM_PLUS,   "+"},
		{VK_OEM_COMMA,  "<"},
		{VK_OEM_MINUS,  "-"},
		{VK_OEM_PERIOD, ">"},
		{VK_OEM_2,      "?"},
		{VK_OEM_3,      "~"},
		{VK_OEM_4,      "["},
		{VK_OEM_5,      "|"},
		{VK_OEM_6,      "]"},
		{VK_OEM_7,      "\""},
};
